# Site settings
title: Hanz Blog Blog
email: hanzblog1@gmail.com
description: "Write your site description here"
baseurl: ""
url: "http://www.hanzlife.com"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
