# Site settings
title: Hanz Life
email: hanzblog1@gmail.com
description: "A blog for Hanz"
baseurl: ""
url: "http://www.hanzlife.com"
twitter_username:
github_username:
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
